apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-{{ .Values.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}-container
        image: "{{ .Values.container.image }}:{{ .Values.container.imagetag }}"
        ports:
        - containerPort: {{ .Values.container.port }}

